---
# Pre-Save Secret Detection Hook - STARTER
# Location: .claude/hooks/pre-save-secrets.yaml

name: pre-save-secret-detection
description: Scans files for secrets before saving
trigger: save
files:
  - "*.ts"
  - "*.tsx"
  - "*.js"
  - "*.jsx"
  - "*.json"
  - "*.env*"
exclude:
  - "node_modules/**"
  - "dist/**"
  - ".git/**"
  - "**/*.test.ts"
script: detect-secrets.ts
fail_action: block
timeout: 5000
---

## Secret Detection Patterns

TODO: Define patterns to detect:
1. AWS Access Keys (AKIA...)
2. Passwords in code
3. API keys
4. Private keys
5. Database connection strings
6. JWT tokens

## Output Format

Success:
```json
{
  "success": true,
  "errors": [],
  "warnings": [],
  "files_checked": 1
}
```

Failure:
```json
{
  "success": false,
  "errors": [
    "Line 15: Potential AWS Access Key detected: AKIAIOSFODNN7EXAMPLE"
  ],
  "warnings": [],
  "files_checked": 1
}
```
