---
# Pre-Commit Test & Coverage Hook - STARTER
# Location: .claude/hooks/pre-commit-tests.yaml

name: pre-commit-test-suite
description: Runs tests and checks coverage before commits
trigger: commit
script: run-tests-and-coverage.ts
parallel: true
fail_action: block
timeout: 60000
stages:
  - lint
  - test
  - coverage
---

## Test Requirements

TODO: Define requirements:
- All tests must pass
- Coverage must be >= 80%
- No console.log in production code
- Branch naming convention: feature/XXX-description

## Stages

1. **Lint Stage**
   - Run ESLint/Prettier
   - Check code style
   - Fix auto-fixable issues

2. **Test Stage**
   - Run full test suite
   - Check for test failures
   - Verify test files exist

3. **Coverage Stage**
   - Generate coverage report
   - Verify threshold (80%)
   - Check for uncovered critical paths

## Output Format

```json
{
  "success": true|false,
  "stages": [
    {
      "name": "lint",
      "success": true,
      "errors": [],
      "warnings": ["Unused import in file.ts"]
    },
    {
      "name": "test",
      "success": true,
      "tests_passed": 45,
      "tests_failed": 0
    },
    {
      "name": "coverage",
      "success": true,
      "coverage_percent": 87
    }
  ],
  "total_duration_ms": 8500
}
```
